# Equilibrio ácido-base

$\require{mhchem}$

$\newcommand{\conc}[1]{\left[ \ce{#1} \right]}$

## Soluciones reguladoras

*Una solución amortiguadora (regulada o buffer) se opone a cambios de pH cuando se le añaden ácidos o bases, o cuando se diluye*. Una solución reguladora está compúesta por la mezcla de un ácido débil y su base conjugada ó una base débil y su ácido conjugado, en esta mezcla el ácido y su base conjugada deben estar en cantidades comparables (dentro de una proporción de 1:10 ó 10:1) para funcionar eficazmente. Esto quiere decir que para preparar una solución reguladora existen principalmente tres opciones diferentes.

::: {.example}
Se mezcla un ácido débil y una base fuerte, pero debe cumplir que $c(\ce{HA}) > c(\ce{NaOH})$.
:::

::: {.example}
Se mezcla un ácido débil y una sal del ácido débil, pero debe cumplir que $c(\ce{HA}) \approx c(\ce{NaA})$.
:::

::: {.example}
Por último la opción menos usada es mezclar la sal del ácido débil y un ácido fuerte, pero debe cumplir que $c(\ce{NaA}) > c(\ce{HCl})$.
:::

```{r tables-common-buffers, echo=FALSE}
x <- c("Ácido ftálico/hidrogeno ftalato de potasio",
       "Ácido acético/acetato de sodio",
       "Hidrogeno ftalato de potasio/ftalato de potasio",
       "Dihidrógeno fosfato de potasio/hidrógeno fosfato de potasio",
       "Ácido bórico/borato de sodio",
       "Glicina/glicinato de sodio",
       "Hidrógeno fosfato de potasio/fosfato de potasio")
y <- c("2.2 - 3.8",
       "3.4 - 5.9",
       "4.0 - 6.2",
       "5.8 - 8.0",
       "7.8 - 10.0",
       "9.5 - 11.7",
       "11.0 - 12.0")
df <- data.frame(x, y)
colnames(df) <- c("Solución reguladora", "Rango aproximado de pH")

knitr::kable(df, caption = 'Algunos reguladores comunes')
```

### Capacidad reguladora

La capacidad de un regulador, $\beta$, es una medida de la resistencia de la disolución a cambiar de pH, cuando se le añade un ácido o una base fuerte. La capacidad de un regulador se define como [@VanSlyke1922]:

$$\beta = \frac{d\ c(\text{b})}{d \text{ pH}} = - \frac{d\ c(\text{a})}{d \text{ pH}}$$

donde $c(\text{a})$ y $c(\text{b})$ es la cantidad de sustancia de ácido fuerte (por ejemplo, $n(\ce{HNO3}$)) y de base fuerte (por ejemplo, $n(\ce{NaOH})$) por litro necesaria para producir un cambio de una unidad de pH. Cuanto mayor es el valor de $\beta$, más resistente es el regulador a un cambio de pH.

Para un ácido débil monoprótico la capacidad reguladora será:

$$\beta = \ln\left(10\right) \left(\conc{H3O+} +\conc{HO-} + c(\ce{HA})_{Total} \times \alpha_0 \times \alpha_1 \right) $$
donde $\alpha_0$ y $\alpha_1$ corresponden a la especie ácida y su base conjugada, respectivamente. Para un ácido poliprótico cambia la ecuación a:

$$\beta = \ln\left(10\right) \left(\conc{H3O+} +\conc{HO-} + c(\ce{HA})_{Total} \times \sum_{i=0}^{n-1} \sum_{j = i+1}^n \left(j-i\right)^2 \alpha_i \times \alpha_j \right) $$
